FROM ruby:3.4.6

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client yarn

WORKDIR /app

COPY Gemfile* ./
RUN bundle install --without development test

COPY . .

ENV RAILS_ENV=production

RUN bin/rails assets:precompile

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
