name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels:
  - enhancement
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Please provide details about the feature you would like to request.**
  - type: input
    id: feature_name
    attributes:
      label: Feature Name
      description: A short name for your feature
      placeholder: e.g., Dark Mode
      required: true
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Explain the feature in detail
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: How will this feature help users or improve the project?
