name: General Issue
description: Report a general issue or question
title: "[ISSUE] "
labels: []
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: Issue Title
      description: Summarize the issue in a few words

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Explain the issue or question in detail
      