openapi: 3.1.0
info:
  title: Rails API
  version: 0.1.0

paths:
  /:
    get:
      summary: Serve Home Page
      operationId: serve_home_page__get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string

  /register:
    get:
      summary: Serve Register Page
      operationId: serve_register_page_register_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string

  /login:
    get:
      summary: Serve Login Page
      operationId: serve_login_page_login_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string

  /weather:
    get:
      summary: Serve Weather Page
      operationId: serve_weather_page_weather_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string

  /api/search:
    get:
      summary: Search
      operationId: search_api_search_get
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
            title: Q
      responses:
        '200':
          description: Successful search
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestValidationError'

  /api/weather:
    get:
      summary: Get current weather for a city/centrum of a state
      operationId: weather_api_weather_get
      parameters:
        - name: city
          in: query
          required: true
          description: Name of the city to fetch weather for
          schema:
            type: string
            example: Copenhagen
      responses:
        '200':
          description: Successful fetch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestValidationError'

  /api/register:
    post:
      summary: Register
      operationId: register_api_register_post
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_register_api_register_post'
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /api/login:
    post:
      summary: Login
      operationId: login_api_login_post
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_api_login_post'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /api/logout:
    get:
      summary: Logout
      operationId: logout_api_logout_get
      responses:
        '200':
          description: Successful logout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

components:
  schemas:
    AuthResponse:
      type: object
      title: AuthResponse
      properties:
        id:
          type: integer
          nullable: true
          title: User ID
        username:
          type: string
          nullable: true
          title: Username
        message:
          type: string
          nullable: true
          title: Message
      description: Standard authentication response.

    Body_login_api_login_post:
      type: object
      title: Body_login_api_login_post
      required:
        - username
        - password
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password

    Body_register_api_register_post:
      type: object
      title: Body_register_api_register_post
      required:
        - username
        - email
        - password
        - password_confirmation
      properties:
        username:
          type: string
          title: Username
        email:
          type: string
          title: Email
        password:
          type: string
          title: Password
        password_confirmation:
          type: string
          title: Password Confirmation

    ErrorResponse:
      type: object
      title: ErrorResponse
      properties:
        message:
          type: string
          title: Message
      description: Standard error message.

    HTTPValidationError:
      type: object
      title: HTTPValidationError
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail

    RequestValidationError:
      type: object
      title: RequestValidationError
      properties:
        statusCode:
          type: integer
          title: Statuscode
          description: HTTP status code. Defaulting to HTTP 422 Unprocessable Entity.
          default: 422
        message:
          type: string
          nullable: true
          title: Message
          description: Detail of the validation error

    SearchResponse:
      type: object
      title: SearchResponse
      required:
        - data
      properties:
        data:
          type: array
          title: Data
          description: List of route search results.
          items:
            $ref: '#/components/schemas/SearchResult'

    SearchResult:
      type: object
      title: SearchResult
      properties:
        title:
          type: string
          title: Title
        url:
          type: string
          title: URL
        content:
          type: string
          title: Content

    ValidationError:
      type: object
      title: ValidationError
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type